### ISSUE TITLE
User Story: see all the lists I have created

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/lunar-lists#10]
In order to **see all the lists I have created** as a **user**, I can **navigate to my saved lists**

### Acceptance Criteria:
- easy to understand table of saved lists
- options to view a list
### Tasks:
- [x] create table view of the lists model
- [x] create navigation bar with link to saved lists
- [x] add h2 title
- [x] add tutorial text explaining how to view a list
