### ISSUE TITLE
User Story: remove a saved to do list

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/lunar-lists#11]
In order to **remove a saved to do list** as a **user**, I can **press the delete button when viewing the list*

### Acceptance Criteria:
- confirmation screen
- notifications
- user can only delete their own lists and not that of another user
### Tasks:
- [x] add delete list button to list view template
- [x] add confirmation screen
- [x] check if user owns list
