### ISSUE TITLE
User Story: delete account

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/lunar-lists#12]
In order to **remove my account from the website** as a **user**, I can **navigate to my account page and click on the delete account link**

### Acceptance Criteria:
- confirmation screen
- user can only delete their own account
### Tasks:
- [x] create account settings template
- [x] add button to delete account
- [x] add confirmation screen
- [x] add user account check to make sure user has the right to do so
