### ISSUE TITLE
User Story: notifications

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/lunar-lists#13]
In order to **be certain of what has just changed** as a **user**, I can **see notifications for every action I have committed**

### Acceptance Criteria:
- appears on screen
- eye catching
- not annoying
### Tasks:
- [x] confirmation on registration
- [x] confirmation on login
- [x] confirmation on item created
- [x] confirmation on item successful edit
- [x] confirmation item was deleted (first make sure they are certain before action and notification)
