### ISSUE TITLE
User Story: change my password

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/lunar-lists#17]
In order to **change my password** as a **user**, I can **navigate to my account page and press the change password link**

### Acceptance Criteria:
- require new password to be retyped to increase likelihood of user remembering their new password
- ensure password is only updated for the correct user
### Tasks:
- [x] add change password button to account settings page
- [x] allow user to update their password
- [x] add submit button
- [x] show confirmation notification after redirecting
