### ISSUE TITLE
User Story: change email address

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/lunar-lists#18]
In order to **change my email address** as a **user**, I can **navigate to my account page and press the change email address link**

### Acceptance Criteria:
- ensure email is only updated for the correct user
### Tasks:
- [ ] add change email button to account settings page
- [ ] allow user to update their email
- [ ] add submit button
- [ ] show confirmation notification after redirecting
