### ISSUE TITLE
User Story: see if the user email address has been verified

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/lunar-lists#2]
In order to **ensure real people are signing up** as an **admin**, I can **see if the user email address has been verified**

### Acceptance Criteria:
- all new users receive an email on signing up
- clicking the link in the email allows for the user to verify their account
### Tasks:
- [ ] add verified field to user model
- [ ] prevent access to account until account is verified
- [ ] create email template
- [ ] create activation link
