### ISSUE TITLE
User Story: use case examples

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/lunar-lists#23]
In order to **understand what the website is for** as a **user**, I can **see example lists on the homepage**
### Acceptance Criteria:
- show multiple use cases
- have clear text explaining what the examples are for
- everyday uses
### Tasks:
- [x] Example Lunar Lists heading
- [x] brief paragraph explaining the list uses
- [x] at least one example displayed
