### ISSUE TITLE
User Story: specifiy task/list/user in confirmation modal

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/lunar-lists#25]
In order to **be certain of what item I am deleting** as a **user**, I can **see the task or list name mentioned in the delete confirmation modal**
### Acceptance Criteria:
- link to the specific task
- fit the layout of the modal
### Tasks:
- [ ] add list title to delete list modal
- [ ] add user name to delete account modal
- [ ] add task description to delete task modal
