### ISSUE TITLE
User Story: see how many tasks I have left to complete

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/lunar-lists#5]
In order to **see how many tasks I have left to complete** as a **user**, I can **see a tally of how many tasks I have completed out of the total**

### Acceptance Criteria:
- make it obvious
- ensure that it updates with every checkbox ticked
### Tasks:
- [ ] create attribute for tasks complete and total tasks on list model
- [ ] create attribute for is_complete on task model
- [ ] add checkbox to is_complete
- [ ] ensure when checkbox is ticked, it updates the data
- [ ] make tasks_complete count how many checkboxes have been ticked
- [ ] make total_tasks count how many tasks are listed
- [ ] display results on list table
