### ISSUE TITLE
User Story: create an account

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/lunar-lists#6]
In order to **create an account** as a **user**, I can **click the create account button**

### Acceptance Criteria:
- good UX
- clearly labelled
- easy to find
### Tasks:
- [x] create button link to 'create an account' page
- [x] create user model
- [x] create HTML form
- [x] only allow one instance of an email address
- [x] add a submit button to form
