### ISSUE TITLE
User Story: create a to do list

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/lunar-lists#7]
In order to **keep track of a day’s tasks** as a **user**, I can **create a to do list**

### Acceptance Criteria:
- be intuitive
- be minimal
### Tasks:
- [x] create tasks model
- [x] create lists model
- [x] create tasks, lists template
- [x] create tasks, lists view
- [x] add create list button
