### ISSUE TITLE
User Story: add an entry to a to do list

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/lunar-lists#8]
In order to **add an entry to a to do list** as a **user**, I can **click the add task button and type out the new entry before submitting**

### Acceptance Criteria:
- minimal steps to add task to list
### Tasks:
- [x] add task button on list view
- [x] takes you back to create a list view
- [x] text field for user to enter new task
