### ISSUE TITLE
User Story: remove an entry from a to do list

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/lunar-lists#9]
In order to **remove an entry from a to do list** as a **user**, I can **select the desired task and then click the 'delete selected task' button from the edit screen**

### Acceptance Criteria:
- intuitive design
- confirmation screen
- notifications
### Tasks:
- [x] add edit view for tasks
- [x] add delete selected task button
- [x] add confirmation screen with the option to cancel
- [x] add notification confirming deletion
